index:
    path: /
    controller: App\Controller\DefaultController::index

hello:
    path: /hello/{name}
    controller: App\Controller\DefaultController::hello

create:
    path: /create
    controller: App\Controller\DefaultController::createPost

list:
    path: /list
    controller: App\Controller\DefaultController::listPosts
